---
name: build-and-test
on: [push, release]
jobs:
  test-source-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package from source
        run: pip install -e .
      - name: Test package from source
        run: |
          python -c "import paperscraper"
          python -m pytest -sv paperscraper
  verify-current-pypi-install:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install package from PyPI
        run: |
          python -m pip install --upgrade pip
          pip install paperscraper
          pip install pytest
      - name: Test package from PyPI
        run: |
          python -c "import paperscraper"
          python -c "import paperscraper.pdf"
          python -c "import paperscraper.arxiv"
          python -c "import paperscraper.scholar"
          python -c "import paperscraper.plotting"
          python -c "import paperscraper.pubmed"
          python -c "import paperscraper.get_dumps"
          python -c "import paperscraper.server_dumps"
          python -c "import paperscraper.tests"
          python -c "import paperscraper.impact"


