---
name: PyPI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify-master-for-potential-pypi-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Install from built distribution
      run: |
        pip install dist/*

    - name: Run tests
      run: |
        python -m pytest paperscraper
